export const LOGIN="/auth/login"
export const SIGNUP ="/auth/register"

export const ALL_CRAFT="/craft/getall"
export const ADD_CRAFT="/craft/add"
export const GET_CRAFT_BY_CATEGORY="/craft/filtercategory/"
export const RECENT_CRAFT="/craft/mostrecent"
export const SEARCH_CRAFT="/craft/search/"
export const CREATORS_CRAFT="/craft/creator/"

export const ADD_TO_CART="/order/addtocart/"
export const BUY_ITEM="/order/buyItem"
export const BUY_ORDER="/order/buy"
export const REMOVE_FROM_CART="/order/removefromcart/"
export const CHANGE_ITEM_QUANTITY="/order/itemquantity"
export const CART="/order/cart"
export const ORDER_TOTAL="/order/ordertotal"